version: '3'

services:
  rust-remote:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    network_mode: host 
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
